name: Triggered Workflow

on: push

jobs:
  Triggered-Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
